name: Documentation
# This job builds and deploys documenation to github pages.
# It runs on every push to master.
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* 0 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: tendermintdev/docker-website-deployment
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: "cosmos/ibc-go"

      - name: Install and Build 🔧
        run: |
          apk add rsync
          make build-docs LEDGER_ENABLED=false
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/output
